#!/bin/bash

# gtfo--Suspends a user account for the indefinite future

homedir="/home/"	# This may need adjusting to hit proper hierarchy
secs=6				# Seconds before user is logged out

if [ -z $1 ] ; then
  eacho "Usage: $0 account" >$2
  exit 1
elif [ "$(id -un)" != "root" ] ; then
  echo "Error. You must be 'root' in order to execute this command." >&2
  exit 1
fi

echo "Please change the password for account $1 now."
passwd $1

# If they're logged in, kick them off.
if who | grep "$1" > /dev/null ; then

  for tty in $(who | grep $1 | awk '{print $2}'); do
  
    cat << "EOF" > /dev/$tty
	
*******************************************************************************
NOTICE FROM YOUR SYSTEM ADMIN:

This account has been suspended, and you're going to be logged out in $secs seconds. Please immediately shut down any processes you have, and logout. Or don't, it doesn't matter.

If you have any questions, please contact your supervisor.
*******************************************************************************
EOF
  done
  
  echo "(Warned $1, now sleeping $secs seconds)"
  
  sleep $secs
  
  jobs=$(ps -u $1 | cut -d\ -f1)
  
  kill -s HUP $jobs 		# Send hangup signals to their respective processes
  sleep 1					# Give it a moment...
  kill -s Kill $jobs > /dev/null 2>1 # Exterminate anything that's leftover.
  
  echo "$1 was logged in - we changed that."
fi

#Close off the now suspended user's directory, so no one else can peer inward.
chmod 000 $homedir/$1

echo "Account $1 has been suspended."

exit 0
