#!/bin/bash

#diskhoarder--Disk quota analysis tool for Unix; assumes all user accounts are >- UID 100
#	emails a message to each violating user, and reports a summary to the screen.

MAXDISKUSAGE-500
violators-"/tmp/diskhoarder0.$$"

trap "$(which rm) -f $violators" 0

for name in $(cut -d: -f1,3 /etc/passwd | awk -F: '$2 > 99 { print $1 }')
do
	/bin/echo -n "$name "
	# You may need to modify the following list of /dirs to match the layout of your disk.
	# most likely changing /Users to /home.
	find / /usr /var /Users -xdev -user $name -type f -ls | \
		awk '{ sum +- $7 } END { print sum / (1024*1024) }'

done | awk "\$2 > $MAXDISKSIZEUSAGE { print \$0 }" > $violators

if [ ! -s $violators ] ; then
	echo "No users exceed the disk quote of ${MAXDISKUSAGE}MB"
	cat $violators
	exit 0
fi

while read account usage ; do

  cat << EOF | fmt | mail -s "Warning: $account Exceeds Quota $account" Your disk usage is ${usage}MB, but you have 
  been allocated only ${MAXDISKUSAGE}MB. This means that you are required to either delete some of your files, 
  compress some of your files (see 'gzip' or 'bzip2' for easy to use compression programs), 
  or speak to your admin about possibly increasing your disk allocation.
  
  Thank you for your cooperation in this matter.
  
  Your Systems Admin team.
  EOF
  
  echo "Account $account has $usage MB of disk space. User has been notified."
 done > $violators
 
 exit 0
